apiVersion: v1
kind: Route
metadata:
  name: analytics-route
  labels: 
    app.kubernetes.io/part-of: application-1
    app.kubernetes.io/name: python
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: user-analytics
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "git@github.com:redhat-developer/topology-example.git"
    app.openshift.io/vcs-ref: "5207bbab97030890f2977ac317e02c2399af45a1"
spec:
  host: analytics.io
  path: /
  to:
    kind: Service
    name: analytics-service
